# PPO Hyperparameters
ppo:
  learning_rate: 1e-4
  n_steps: 1024
  batch_size: 128
  n_epochs: 5
  gamma: 0.99
  gae_lambda: 0.95
  clip_range: 0.1
  clip_range_vf: 0.1
  ent_coef: 0.02
  max_grad_norm: 0.5
  vf_coef: 0.25

# Environment
env:
  symbols: ["EURUSD"]
  timeframes: [1, 5, 15]
  window_size: 30
  max_leverage: 5.0