# PPO Hyperparameters
ppo:
  learning_rate: 0.0004
  n_steps: 2048
  batch_size: 256
  n_epochs: 5
  gamma: 0.99
  gae_lambda: 0.95
  clip_range: 0.2
  clip_range_vf: 0.1
  ent_coef: 0.01
  max_grad_norm: 0.5
  vf_coef: 0.25

# Environment
env:
  symbols: ["EURUSD"]
  timeframes: [15]
  window_size: 50
  max_leverage: 2.0