algorithm: impala  # or 'ppo'

# Enhanced PPO Hyperparameters for Trading with Improved Architecture
# Model/Transformer hyperparameters
model:
  features_dim: 256
  transformer:
    d_model: 256
    nhead: 8
    num_layers: 4
    dropout: 0.1
ppo:
  learning_rate: 0.0001     # Lower for complex transformer
  n_steps: 8192             # Larger rollouts for better exploration
  batch_size: 512           # Large batches for stable transformer training
  n_epochs: 20              # More epochs due to complex architecture
  gamma: 0.999              # Higher discount for long-term trading patterns
  gae_lambda: 0.98          # High GAE for proper advantage estimation
  clip_range: 0.1           # Conservative clipping for stable training
  clip_range_vf: 0.2        # Value function clipping
  ent_coef: 0.001           # Lower entropy for focused exploration
  max_grad_norm: 1.0        # Higher gradient norm for transformer
  vf_coef: 0.8              # Higher value function coefficient
  normalize_advantage: true # Important for transformer training

# Enhanced Environment Configuration with Realistic Market Simulation
env:
  symbols: ["EURUSD"]
  timeframes: [15]
  window_size: 100          # Longer window for transformer attention
  max_leverage: 2.0
  
  # Enhanced feature engineering
  target_variance: 0.95     # Higher variance retention
  min_components: 20        # More components for complex patterns
  max_components: 50        # Allow more features if needed
  
  # Realistic market simulation
  enable_realistic_execution: true
  base_spread_bps: 0.8      # Realistic EURUSD spread
  slippage_factor: 0.15     # Moderate slippage
  liquidity_impact: 0.08    # Volume impact
  
  # Enhanced reward parameters
  reward_scaling: 1.5
  min_reward: -15.0
  max_reward: 15.0
  survival_bonus: 0.01
  leverage_penalty: 0.05
  trade_reward_multiplier: 2.5
  risk_adjusted_reward: true
  drawdown_penalty: 0.3
  early_close_bonus: 0.15
  diversification_bonus: 0.08
  volatility_penalty: 0.08
  position_size_penalty: 0.03
  min_tp_sl_ratio: 2.5      # Higher risk-reward ratio
  atr_multiplier: 1.8       # Dynamic stops