algorithm: impala

# Model/Transformer hyperparameters
model:
  features_dim: 256
  transformer:
    d_model: 256
    nhead: 8
    num_layers: 4
    dropout: 0.1

# Environment Configuration
env:
  symbols: ["EURUSD"]
  timeframes: [15]
  window_size: 100
  reward_scaling: 2.0
  min_reward: -10.0
  max_reward: 10.0
  survival_bonus: 0.02
  leverage_penalty: 0.02
  trade_reward_multiplier: 2.0
  drawdown_penalty: 0.2
  early_close_bonus: 0.1
  volatility_penalty: 0.05
  position_size_penalty: 0.02
  max_leverage: 20.0
  min_tp_sl_ratio: 1.8
  atr_multiplier: 2.2
  use_cached_features: true
  execution_cost_penalty_weight: 0.1
  max_daily_drawdown: 0.2

# IMPALA training hyperparameters
impala:
  learning_rate: 0.0005
  batch_size: 512
  minibatch_size: 100
  num_rollout_workers: 2
  rollout_fragment_length: 50
  num_gpus: 1